services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: L
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: app
    ports:
      - "5431:5432"
    volumes:
      - OPP:/var/lib/postgresql/data
    networks:
      - BTV
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 50s
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first



  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - BTV


volumes:
  OPP:

networks:
  BTV:

